- Makefile
- env_sample.sh
- src/alert/Dockerfile
- src/finding/Dockerfile
- src/iam/Dockerfile
- src/project/Dockerfile
- src/report/Dockerfile
> rm: GOPRIVATE

- src/alert/go.mod
- src/alert/go.sum
- src/project/go.mod
- src/project/go.sum
> update proto project module

- src/finding/go.mod
- src/finding/go.sum
- src/finding/service_batch.go
- src/finding/service_batch_test.go
- src/finding/service_finding.go
- src/finding/service_pend.go
- src/finding/service_resource.go
- src/finding/service_setting.go
PutResourceBatch APIの実装です
github.com/golang/protobuf/ptypes/empty がdeprecatedになっていたのでその対応も入っています。
> Put resource batch

- main.go
- pkg/server/server.go
Graceful Shutdownを実装しました。
リクエストの処理を終えたからserverをshutdownするようにします。
> Implement gracefule shutdown

- go.mod
- go.sum
- pkg/db/db.go
- pkg/db/finding_test.go
grpcサーバーの統合の際、消してしまったテストコードを復活させます
> Restore repository test

- go.sum
- main.go
- pkg/server/server.go
> Implement healthz endpoint

- codebuild/release/buildspec-manifest.yml
> fix: repository name

- pkg/db/finding.go
- pkg/db/finding_test.go
#279 SQLのエスケープ処理漏れの対応です。
close https://github.com/ca-risken/core/issues/279
> fix: sql escape

- pkg/server/alert/alert_analyze_test.go
- pkg/server/project/project_test.go
mock constructorを使うようにしたのと、importの最適化です
https://github.com/vektra/mockery#mock-constructors
> Fix test code

- Makefile
port-forwardなしでAPI実行できるコマンドに修正します
> fix: call API without port-forward

- pkg/server/alert/alert_test.go
- proto/alert/validator.go
- proto/alert/validator_entity_test.go
- proto/alert/validator_test.go
> add: webhook url validation

- pkg/server/alert/alert.go
- pkg/server/alert/alert_analyze.go
- pkg/server/alert/alert_analyze_test.go
- pkg/server/alert/alert_notification.go
- pkg/server/alert/alert_notification_test.go
- pkg/server/alert/alert_test.go
- pkg/server/alert/logger.go
- pkg/server/alert/service.go
- pkg/server/server.go
> fix: logger

- pkg/db/iam.go
ListUserでNameパラメータを設定していた際に、UserIdpKeyの値も検索できるように修正します
> fix db list user

- pkg/db/iam.go
- pkg/db/mocks/IAMRepository.go
未使用のIFを削除します
(実装自体はpkg内部で使用しているので残しています)
> rm: unused IF

- Makefile
- pkg/db/mocks/ReportRepository.go
- pkg/db/report.go
- pkg/db/report_test.go
- pkg/server/alert/service.go
- pkg/server/finding/service.go
- pkg/server/iam/service.go
- pkg/server/project/service.go
- pkg/server/report/report.go
- pkg/server/report/report_test.go
- pkg/server/report/service.go
- proto/report/mocks/ReportServiceClient.go
- proto/report/mocks/ReportServiceServer.go
- proto/report/service.pb.go
- proto/report/service.proto
ReportFindingのパージAPIを追加します（1年以上前の集計データは削除します）
> add: purge finding report

- pkg/server/alert/alert_analyze.go
- pkg/server/alert/alert_notification_test.go
https://github.com/ca-risken/core/pull/320
> アラートの内容に変更があった（Findingの内容が変更された）場合は通知する
上記の仕様が満たせてなかったため修正します。
> fix: alert

- pkg/server/alert/alert_notification.go
- pkg/server/alert/alert_slack.go
Slack通知の修正です
- 通知の頭の文章の修正
- notificationがlocale対応していなかった問題があったことへの修正
> fix notification

- go.mod
- go.sum
> update: database

- main.go
- pkg/ai/openai.go
- pkg/server/finding/service.go
- pkg/server/server.go
ChatGPTモデルを固定にしていましたがオプション化します
> add: gpt model option

- pkg/db/alert.go
- pkg/model/alert.go
- pkg/server/alert/alert.go
- pkg/server/alert/alert_test.go
Alert生成時にfirst_viewed_atがnullではなく、zero値で登録されてしまっていたためmodelを修正します
> fix first_viewed_at to a pointer

- pkg/server/alert/alert_slack.go
> fix: notify URL

- pkg/ai/openai.go
> fix: generative ai format

- proto/finding/validator.go
- proto/finding/validator_test.go
> fix: note validation

- pkg/server/project/project.go
- pkg/server/project/project_test.go
projectサービスのisActiveに対象のプロジェクトIDを持ったプロジェクトが存在するか調べる処理を追加します
> fix isActive

- pkg/ai/openai.go
生成AIによる解析・要約・提案の精度を上げるために情報量を増やすチューニングを行いたいと思います。
いくつか確認したところ特にSCCやCode系のFindingでは修正方法や影響範囲の説明等の精度が上がる印象です。
（毎回同じ回答になるわけではありませんが）
> fix: finding details

- pkg/ai/openai.go
- proto/finding/validator.go
- proto/finding/validator_test.go
> fix: recommend type length

- Makefile
- main.go
- pkg/server/alert/alert_analyze.go
- pkg/server/alert/alert_notification.go
- pkg/server/alert/alert_notification_test.go
- pkg/server/alert/alert_slack.go
- pkg/server/alert/alert_slack_test.go
- pkg/server/alert/service.go
- pkg/server/server.go
- proto/alert/validator.go
> support: slack app

- pkg/server/alert/alert_slack.go
- pkg/server/alert/service.go
> refactor: handle slack rate limit error

- pkg/ai/openai.go
- pkg/ai/openai_test.go
> fix: prompt

- pkg/server/finding/finding_triage.go
- pkg/server/finding/finding_triage_test.go
トリアージデータの抽出、結果の反映がうまくできてないバグがありました。
- jsonキーのtypo
- assesment結果の反映漏れ
- 調整後のスコアの反映漏れ
- エクスプロイト評価の修正
- その他バグ修正、テスト追加
> fix: bug fix

- pkg/server/finding/finding_triage.go
- pkg/server/finding/finding_triage_test.go
EFFICIENTの場合はスコア調整しないようバランスします
> fix: utility assessment

- pkg/db/organization_iam.go
- pkg/db/organization_iam_test.go
org iamのバグを一部修正しました
また、テストをDRYにするためにクエリを定数化してテストからも参照できるようにしました。
> fix: org iam

- pkg/server/organization/organization.go
- pkg/server/organization/organization_test.go
ReplyOrganizationInvitationしたとき（ProjectがOrganizaitonからの招待を承諾または拒否したとき）、REJCTEDのときだけOrganizationProjectを削除するようにします。
Projectが誤って承諾したものをREJECTしたときにOrgから脱退できるようにするためです。
> add: data consistent logic

- pkg/db/organization_iam.go
OrganizationのRoleとPolicyの読み取りを、ProjectのIAMに合わせてMasterにし、ラグに対処します
https://github.com/ca-risken/core/blob/master/pkg/db/iam.go#L232
> fix: slave to master

- pkg/ai/chat.go
チャット機能にもGetFindingDataのツールを追加します。
これによりユーザからのチャット応答時に実際のデータを検索して回答できるようになります
> add: chat tools

- Makefile
- main.go
- pkg/ai/chat.go
- pkg/ai/finding.go
- pkg/ai/report.go
- pkg/ai/responses.go
- pkg/ai/tool_get_finding_data.go
ReasoningModelの方はGPT5にアップグレードしておきます
> upgrade: reasoning model
