src/finding/service_recommend.go

レコメンド登録で分散トランザクションの問題が発生していたので修正します
（レコメンド登録時にチェックしてるFindingデータの参照先をslaveではなくmasterのDBに変更）

fix: recommend transaction

---

pkg/server/alert/alert_condition.go
pkg/server/alert/alert_test.go

convertNotification失敗時にWebhookURLがマスキングされないままレスポンスとして返されていた
修正対応として、convertNotification失敗時にエラーレスポンスを返すよう修正します

fix alert convert notification

---

pkg/server/finding/finding.go
pkg/server/finding/finding_batch.go
pkg/server/finding/finding_batch_test.go
pkg/server/finding/finding_setting.go
pkg/server/finding/finding_test.go
pkg/server/finding/logger.go
pkg/server/finding/pend.go
pkg/server/finding/pend_test.go
pkg/server/finding/recommend.go
pkg/server/finding/recommend_test.go
pkg/server/finding/service.go
pkg/server/iam/access_token.go
pkg/server/iam/auth.go
pkg/server/iam/auth_test.go
pkg/server/iam/logger.go
pkg/server/iam/service.go
pkg/server/iam/user.go
pkg/server/iam/user_test.go
pkg/server/project/logger.go
pkg/server/project/project.go
pkg/server/project/project_test.go
pkg/server/project/service.go
pkg/server/report/logger.go
pkg/server/report/report.go
pkg/server/report/service.go
pkg/server/server.go

logger.goを削除し、loggerを生成するところを一つにしました。
alertは変更が入る予定であるため、今回は対応を見送ります。
また、不要と思われるログは一部削除しました。

DRY logger

---

pkg/server/alert/alert_analyze.go

AnalyzeAlertAllのgoroutine内部の処理が失敗した際に、通知ログを出力するように変更。
AnalyzeAlertを非同期化するとgoroutineを使わなくて良くなるので、そのあとに処理を直列化してAnalyzeAlertAllもエラーを返すようにする予定。
このPRはそれまでの暫定対応です。

Notify fail to goroutine

---

pkg/db/finding.go
pkg/db/finding_test.go

パフォーマンスの問題でSQLで `regexp` 条件を使用している箇所をLIKEに変更します。
また、DBのindexが利用されるよう前方一致検索に変更します
（これまで、部分一致検索を許容していたので機能劣化になります。RISKEN内のシステムで部分一致を利用しているユースケースがないのと、システムパフォーマンスを優先する判断です）
この修正で影響を受けるAPIはいかになります
- ListFinding(resrouce_name, data_source)
- BatchListFinding(resrouce_name, data_source)
- ListResource(resrouce_name)

rm: regexp SQL

---

main.go
pkg/db/db.go
pkg/db/iam.go

pkg/db配下のfunctionで、発生したerrorを呼び出し元に返していなかったものがあったので呼び出し元に返すよう変更。
`db.NewClient`は、function内でexitするのではなくmainでexitするためにerrorを返すようにしました。

Resolve missing error in pkg/db

---

pkg/server/alert/alert_analyze.go
pkg/server/finding/finding_setting.go
pkg/server/server.go

pkg/server配下のfunctionで、発生したerrorを呼び出し元に返していなかったものがあったので呼び出し元に返すよう変更
grpcのclientを生成するfunctionは、function内でexitするのではなく呼び出し元でハンドリングするためにerrorを返すようにしました。

Resolve missing error in pkg/server

---

pkg/db/alert.go

AlertHistoryのサイズが大きすぎて、gRPCのエラーが発生する問題への暫定対応です
取得するAlertHistoryの数に制限をかけます

fix listAlertHistory

---

pkg/server/alert/alert_analyze.go

Slackアラート検知からのユーザ行動解析のため、パラメータを追加します。
これにより、アラート画面の遷移を識別できるようにします。

add: url param for user analysiss

---

pkg/server/alert/alert_slack.go

alert_slack.go内でのapploggerの使用部分を削除します。
以下の指摘への対応です。
https://github.com/ca-risken/core/pull/288/files#r1018575468

rm: applogger in alert_slack.go

---

Makefile
go.mod
go.sum
pkg/db/db.go
pkg/db/finding.go

Deadlockの対処法として[MySQL公式ドキュメント](https://dev.mysql.com/doc/refman/5.6/ja/innodb-deadlocks.html)を参考にアプリ側にリトライの仕組みを導入しようと思います。
全体に導入するというより、まずは実際にDeadlockが発生している処理にしぼって設定する方針です。
Backoffの実装は以下のライブラリを使いました。
https://pkg.go.dev/github.com/cenkalti/backoff/v4
リトライのロジックは↓準拠のものになっています。
https://en.wikipedia.org/wiki/Exponential_backoff

add: exponential backoff

---

pkg/db/iam.go

user_idp_keyが空文字の場合、テーブルに空文字で登録する処理をNULLで登録するように修正します。

fix put user

---

pkg/db/mocks/project.go
pkg/db/project.go
pkg/db/project_test.go
pkg/server/project/project.go
pkg/server/project/project_test.go

プロジェクト削除の方針を変更します。
プロジェクト削除のAPIでは大本のプロジェクトデータを削除のみ行い、後ほど非同期で関連データのパージバッチを動かす方式とします。今回は既存APIのロジック修正のみのPRです。

delete: project

---

pkg/db/project.go
pkg/db/project_test.go

not existsによるSQLはフルスキャンになってしまい、findingテーブル数百万クラスの環境で実行すると15分以上帰ってこない状態になってしまっていました。
DBの負荷も高すぎて定期的に実施できるレベルのパフォーマンスではないため、Clena対象のプロジェクトIDを取得し、プロジェクトID指定でdelete文を発行するように修正しました。
削除対象のプロジェクトIDを取得する箇所はRoleテーブルを参照していますが、通常のユースケースではユーザがプロジェクト削除のオペレーションを実行するのに何らかのロールが必要なため、必ずRoleテーブルにゴミデータが残ることを想定しているためです。

fix: clean SQL

---

pkg/db/iam.go
pkg/db/iam_test.go

listUserReservedのuser_idp_keyによる検索を部分一致に変更します
listUserによる検索と条件を合わせるためです
listUserReservedWithProjectIDに関しては、core内部でのみ使用するため修正しません

fix list-user-reserved

---

pkg/server/alert/alert_analyze.go
pkg/server/alert/alert_analyze_test.go
pkg/server/alert/alert_notification_test.go

アラートの通知タイミングを以下の仕様・制御に変更したい。
- 新規のアラートは通知する
- アラートの内容に変更があった（Findingの内容が変更された）場合は通知する
- 上記以外にリマインダーとして一定期間経過で通知する
- 前回通知からCacheSecond以降のタイミングでリマインド通知を行う
- CacheSecondはデフォルト一ヶ月の値に設定する（WEB側の登録APIのパラメータを修正予定）
- CasheSecondはユーザ側で変更可能とする

fix: alert control

---

main.go
pkg/server/alert/alert_analyze.go
pkg/server/alert/alert_notification_test.go
pkg/server/alert/alert_slack.go
pkg/server/alert/alert_slack_test.go
pkg/server/alert/service.go
pkg/server/server.go

Slack通知に英語/日本語の二つの言語を使用できるよう修正します
デフォルトで使用する言語は環境変数で受け取り、デフォルト値は英語です
notificationのnotify_settingのjsonにlocaleを追加して、そこに`ja`/`en`の指定がある場合はその言語を使用します
以下は補足です
- upsert時のlocaleのバリデーションはしてません
- 異常値の場合にはデフォルト値を使うため問題ないと判断しました
- Web画面では、選択式もしくは自動で入力するためユーザーのミスで異常値が入ることは想定していません
- (意図的に異常値を入れることは可能ですが)

multi language slack notification

---

proto/alert/validator.go
proto/alert/validator_entity_test.go
proto/alert/validator_test.go

WebhookURLのバリデーションを修正します
登録済みのWebhookURLはList,Get時にマスクして表示しています。(プロジェクト内の人が誰でもみれる状況を防ぐ)
これによりWebでは、マスク処理されたURLのみを見ることができるようになっています。
ユーザーがURLを再度確認しにいく作業をなくすために、PutNotificationで登録済みnotificationの更新時にWebhookURLを空にすれば既存の値を適用するようにしていました
現状のバリデーションでは、WebhookURL以外の値の更新時にエラーとなるため上記の目的を満たせなていないことに気づきました
そのため、Notificationの新規作成・更新時に処理を分けるようにします
新規作成時は既存のバリデーション、更新時はWebhookURLが空なのを許容し、存在している場合にはURL形式か検証します

fix webhook_url validation

---

pkg/db/finding.go
pkg/db/finding_test.go

delete文でデータ一括削除を行う実装でしたが、テーブルのデータ量が多い場合に長時間かつ広範囲にテーブルをロックしてしまい、他のDB更新系のAPIに影響が出てしまう事象を確認しました。
ロック状態を回避するために削除対象のIDをselectしてからPK指定でdeleteする形式に変更したいです。

fix: clean api

---

pkg/server/alert/alert.go
pkg/server/alert/alert_test.go
proto/alert/validator.go
proto/alert/validator_test.go

AlertのFirstViewed更新をより正確に計測するために以下の変更を行います
- AlertIDを必須から任意へ変更
- AlertIDが含まれない場合は、該当プロジェクトのAlertを一括で更新する
- AlertIDが含まれる場合は、該当のAlertのみ

fix put alert first viewed

---

pkg/server/alert/alert_slack.go

FirstViewAlertAtの更新にAlertIDを必要としなくなったため、Slack通知のリンクからAlertIDを削除します

fix notification url

---

pkg/server/server.go

grpc_probeが使えるようになったため、readiness probeのために作成していたHTTPヘルスチェックエンドポイントを削除します。
- 余計なものを削除していないか
https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/
https://github.com/ca-risken/internal-community/issues/615

chore: delete http endpoint

---

pkg/server/alert/alert_slack.go

RequestProjectRoleの引数の順序が誤っており、slack appの場合は誤った文言が通知されるようになっていたものを修正します。

fix arg order

---

pkg/server/alert/alert_notification.go

Notificationに既存データが存在する際の更新時の挙動を変更します。
webhookurl設定済み、またはChannelID設定済みの時
=> 新たに設定したものが追加され、どちらの設定も残る
webhookurl設定済みの時、ChannelID指定
=> 既存のwebhookurlの設定が解除され、ChannelIDが設定される
ChannelID設定済みの時、webhookurl指定
=> 既存のChannelIDの設定が解除され、webhookurlが設定される
webhookurl設定済みの時、channelid,webhookurlどちらも新たに設定しない
=> 既存のwebhookurlが残る

fix removing exist data

---

pkg/server/project/project.go
pkg/server/project/project_test.go

デフォルトロールを新たに追加します。
これまで、project-admin-role以外のデフォルトロールは手動で作成していましたが、手動で作成されるロールにもよく使用されるパターンがあることがわかってきました。そのため、以下のパターンを追加します。
- findingだけをチェックしたい場合のロール
- 読み取り専用の権限
コメントに記載してあります

add default role

---

pkg/server/project/project.go

put-alert-first-viewed-atの権限がないと、alertとfindingの画面を開くことができなかったので修正しました。また、viewer権限が間違っていたので修正しました。
動作確認済み
実際にfindingが開くことが可能かどうかはローカルで管理者以外のユーザーを作成してそれにログインする方法がわからなかったため、試せていません。方法をご存知でしたらご教示ください。

add put-alert-first-viewed-at

---

.github/workflows/code-butler.yml

コードレビュー効率化のため、code-butlerを導入します。以下の参考yamlのコピペです。
https://github.com/marketplace/actions/code-butler-for-pr-review

add yaml for ci

---

pkg/server/project/project.go

デフォルトのポリシーが意図した動作になってなかったので修正します

fix: default policy

---

pkg/server/alert/alert_notification.go

通知先が登録されてないとNil参照エラーで落ちてしまうので修正します

fix: nil deriference

---

pkg/db/iam.go
pkg/db/mocks/IAMRepository.go
pkg/server/iam/user.go
pkg/server/iam/user_test.go
proto/iam/validator.go

GetUserのリクエストにて、UserIdpKeyでの検索を可能にします
protoのリクエストパラメータとしては用意されてましたが、validator,dbがuser_idp_keyに対応していなかったので修正
validatorはuser_id,subのどちらかが必須からuser_id,sub,user_idp_keyのどれかが必須に変更しました。

add get user request parameter

---

pkg/db/iam.go
pkg/server/alert/alert_notification_test.go

AdminAPI経由でロール更新が失敗する問題を修正します。
また、Slack関連のテストが失敗してた箇所があったのですが、外部へのHTTPリクエストはmock化してテスト通る形に修正しています

Fix admin bug

---

go.mod
go.sum
main.go
pkg/server/finding/finding.go
pkg/server/finding/finding_triage.go
pkg/server/finding/finding_triage_test.go

- SSVCによる自動トリアージ機能を追加します。
- ChatGPTのモデルのデフォルトがdeprecatedになるため4o-miniに変更します（利用可能で最も安いモデル）

Auto triage

---

pkg/db/organization_iam.go
pkg/db/organization_iam_test.go
pkg/server/organization_iam/policy_test.go

GetOrganizationPolicyが意図しない挙動をするため、修正しました。
具体的にはOrganization IDが0の場合もwhere句にクエリを追加してしまうようになっていました。
他のいくつかのテストも修正を加えています。

fix: get policy

---

pkg/db/finding.go
pkg/db/mocks/FindingRepository.go
pkg/server/finding/finding_batch_test.go
pkg/server/finding/finding_setting.go
pkg/server/finding/finding_test.go

FindingSettingにおいて、リソース名のPrefixマッチをサポートします
例えば、オートスケールされるKubernetesノードなどのケースでは以下の課題があります。
- 短命のノードに脆弱性があるケース
- ノードが生成されるたびにFindingが生成される
- リソース名が完全一致だと対象リソースのコントロールが難しい

support: prefix-match ressource name with finding setting

---

pkg/db/project.go
pkg/db/project_test.go

プロジェクトが削除されたとき、Organization関連のエンティティを削除するため、cleanProjectの処理を追加します
ローカルでmake clean-projectをした時
- Projectが削除されていない場合はOrgProejctとOrgInvitaitonは削除されない
- Projectが削除されている場合はOrgProejctとOrgInvitaitonは削除される
ことを確認しました

refactor: implement deletion of organization invitations and projects
